services:
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: transactions_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@transaction
    container_name: transactions_db_container
    ports:
      - "15432:5432"
    volumes:
      - transactions_db_vol:/var/lib/postgresql/data


volumes:
  transactions_db_vol:
  static:
  media: